"""Initial schema

Revision ID: 903e036678c9
Revises: 
Create Date: 2025-05-22 11:39:01.374331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903e036678c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo_dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipo_dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabricante', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo')
    )
    op.create_table('dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('version_firmware', sa.String(), nullable=False),
    sa.Column('descripcion_ubicacion', sa.String(), nullable=False),
    sa.Column('coordenadas_gps', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tipo_dispositivo_id', sa.Integer(), nullable=True),
    sa.Column('estado_actual', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_dispositivo_id'], ['tipo_dispositivo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('dispositivo_grupo',
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_dispositivos.id'], ),
    sa.PrimaryKeyConstraint('dispositivo_id', 'grupo_id')
    )
    op.create_table('log_estado_dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('mensaje_opcional', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_sensor', sa.String(), nullable=False),
    sa.Column('unidad_medida', sa.String(), nullable=False),
    sa.Column('umbral_alerta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lectura_dato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('valor_leido', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lectura_dato')
    op.drop_table('sensor')
    op.drop_table('log_estado_dispositivo')
    op.drop_table('dispositivo_grupo')
    op.drop_table('dispositivo')
    op.drop_table('tipo_dispositivo')
    op.drop_table('grupo_dispositivos')
    # ### end Alembic commands ###
